### ISSUE TITLE
Fix save rows/obs for vertabrate individuals

### ISSUE THREAD

**Issue by Matheo13** [naturalsolutions/ecoReleve-Data#436]

**Comment by Matheo13** [comment]
![image](https://cloud.githubusercontent.com/assets/9080540/22981589/1ccd2d42-f39d-11e6-8795-60430839800d.png)

Data seems right from front side.
I'm not able to display back side print anymore 4 the moment.
Must be a config in dev.ini

**Comment by romfabbro** [comment]
I will see Back side

**Comment by Matheo13** [comment]
Thx

2017-02-15 16:41 GMT+01:00 romfabbro <notifications@github.com>:

**Comment by romfabbro** [comment]
FK_ProtocoleType is missing on a new row in sub grid

**Comment by Matheo13** [comment]
ok

**Comment by romfabbro** [comment]
normally FK_protocoleType is a hidden column setted with a defaultValue
![image](https://cloud.githubusercontent.com/assets/7631078/22982881/af3b27da-f3a0-11e6-92d5-472df9096d08.png)

defaultValue is a needed feature

**Comment by Matheo13** [comment]
yup I fix it

**Comment by Matheo13** [comment]
https://github.com/NaturalSolutions/ecoReleve-Data/pull/437
